services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
