pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Checkout') {
            steps{
                git branch: 'main', url:'https://github.com/anilgosavi/my-aws-node-app.git'
            }

        }
        stage('Build') {
            steps{
                script{
                    sh 'docker build -t my-node-app .'
                }
            }
        }
        stage('Run tests'){
            steps{
                script{
                    sh 'docker run --rm my-node-app npm test'
                }
            }

        }
        stage('Deploy to Aws'){
            steps{
                script{
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }

        }    
    }
    post{
        always{
            cleanWs()
        }
    }
}

    